#!/usr/bin/env python3
"""Emit CONTROLS.md — the full parameter inventory, page by page, generated
from the same source of truth as everything else (ui_pages + chain_params).
Run after gen_params.py:  python3 tools/list_controls.py
"""
import json, pathlib, re

ROOT = pathlib.Path(__file__).resolve().parent.parent

cfg = json.loads((ROOT / "src/ui_pages.json").read_text())
hdr = (ROOT / "src/dsp/params.h").read_text()
raw = re.search(r'tb_chain_params_json =\n    "(.*)";', hdr).group(1)
chain = {p["key"]: p for p in json.loads(raw.replace('\\"', '"').replace("\\\\", "\\"))}

def fmt_range(p):
    cp = chain.get(p["k"], {})
    t = cp.get("type", p.get("t"))
    if t == "filepath":
        return "file browser", "Init (built-in)"
    if t == "enum":
        opts = cp.get("options", [])
        default = cp.get("default", "")
        shown = " / ".join(opts) if len(opts) <= 8 else f"{len(opts)} options"
        return shown, default
    lo, hi = cp.get("min", "?"), cp.get("max", "?")
    kind = "pot" if (lo, hi) == (0, 127) else "int"
    return f"{lo}..{hi} ({kind})", str(cp.get("default", ""))

lines = [
    "# Tablor — every control, page by page",
    "",
    "Generated by `tools/list_controls.py` from the single parameter source.",
    "Mark anything to cut and the generator removes it everywhere at once",
    "(DSP, device pages, web panel, presets).",
    "",
    "@TOTAL@",
    "",
]

total = 0
for b in cfg["pages"]:
    slots = [s for s in b["slots"] if s]
    total += len(slots)
    lines.append(f"## {b['name']}  ({len(slots)} controls)")
    lines.append("")
    lines.append("| # | Control | Key | Values | Default |")
    lines.append("|---|---------|-----|--------|---------|")
    for i, s in enumerate(slots):
        rng, default = fmt_range(s)
        lines.append(f"| {i+1} | **{s['full']}** | `{s['k']}` | {rng} | {default} |")
    lines.append("")

out = "\n".join(lines).replace(
    "@TOTAL@", f"**Total: {total} controls across {len(cfg['pages'])} pages.**")
(ROOT / "CONTROLS.md").write_text(out + "\n")
print(f"CONTROLS.md written: {total} controls, {len(cfg['pages'])} pages")
